sudo: false
language: java
jdk:
  - openjdk7 # just run openJdk - oraclejdk7
env:
  global:
    - MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=256m"
    - TRAVIS_PYTHON_VERSION="2.7"
cache:
  directories:
  - $HOME/.m2
install:
  - "travis_retry pip install -q sphinx==1.1.3"

script: "travis_wait type sphinx-build"
